services:
  postgres:
    image: postgres:17.2-alpine
    container_name: smart_home_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_DB: smart-home-db
    volumes:
      - /home/smart-home-db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user)"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  init_scripts:

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password